[features]
seeds = false
skip-lint = false
[programs.localnet]
hyperflow = "6khbWKLNioUkCUhEK22oZVd1sa1YKby1biTv5wWY2eo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ruixiantay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
